version: "3"
services:
  mcs1:
    image: ${MCS_IMAGE_NAME}
    shm_size: "512mb"
    hostname: ${PM1}
    restart: always
    env_file:
      - .env
    ports:
      - 172.17.0.1:3307:3306
    volumes:
      - ./data1:/var/lib/columnstore/data1
      - ./storagemanager:/var/lib/columnstore/storagemanager
      - ./mysql_data:/var/lib/mysql:rw
      # - ./scripts/columnstore-init:/usr/bin/columnstore-init:rw

  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mcs1:mcs1
    ports:
      - "172.17.0.1:24781:80"
    environment:
      PMA_HOST: mcs1
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${ADMIN_PASSWORD}
      UPLOAD_LIMIT: 500M
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      - mcs1
